### ISSUE TITLE
Support GS1-128?

### ISSUE THREAD

**Issue by joevandyk** [ankane/barkick#4]
Would something like https://www.scaleprogrammers.com/pdf/GS1%20Barcode%20Breakdown.pdf be something barkick can/should support?

**Comment by joevandyk** [comment]
I have a very very early start on the support here. https://github.com/ankane/barkick/compare/master...joevandyk:gs1_128

Is that something worthwhile to continue? Or should I do this in a new gem?

**Comment by ankane** [comment]
Hey @joevandyk, happy to include support in Barkick. Feel free to submit a PR. The general specification is defined in Section 3.2. https://www.gs1.org/sites/default/files/docs/barcodes/GS1_General_Specifications.pdf

**Comment by ankane** [comment]
Cleaning up issues
