### ISSUE TITLE
#invalid? method

### ISSUE THREAD

**Issue by Spone** [ankane/barkick#6]
Hi! Thanks for a very useful gem :)

Would you consider adding an `#invalid?` method that returns the inverse of `#valid?`, similarly to [ActiveModel](https://api.rubyonrails.org/classes/ActiveModel/Validations.html#method-i-invalid-3F)?

This would make things clearer in some cases:

```diff
- return nil if @isbn.blank? || !Barkick::GTIN.new(@isbn, type: :isbn13).valid?
+ return nil if @isbn.blank? || Barkick::GTIN.new(@isbn, type: :isbn13).invalid?
```

I can dedicate some time to a PR.
Let me know.

**Comment by ankane** [comment]
Hey @Spone, thanks for the suggestion. However, it's not something I'd like to include.

**Comment by Spone** [comment]
Thanks for the reply.
